빅데이터 분석기사 5회 실기 기출 유형
[가격 예측] 중고 자동차
자동차 가격을 예측해주세요!
예측할 값(y): price
평가: RMSE (Root Mean Squared Error)
data: train.csv, test.csv

In [1]:
import numpy as np
import pandas as pd
train = pd.read_csv('train.csv')
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3759 entries, 0 to 3758
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   model         3759 non-null   object 
 1   year          3759 non-null   int64  
 2   price         3759 non-null   int64  
 3   transmission  3759 non-null   object 
 4   mileage       3759 non-null   int64  
 5   fuelType      3759 non-null   object 
 6   tax           3759 non-null   int64  
 7   mpg           3759 non-null   float64
 8   engineSize    3759 non-null   float64
dtypes: float64(2), int64(4), object(3)
memory usage: 264.4+ KB


In [2]:
y = train['price']
x = train.drop(columns=['price'])

In [3]:
x_cat = x.select_dtypes('object')
x_con = x.select_dtypes(exclude='object')

In [4]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
enc = OneHotEncoder(sparse=False)
sc = StandardScaler()
enc.fit(x_cat)
sc.fit(x_con)
x_cat = enc.transform(x_cat)
x_con = sc.transform(x_con)

C:\Users\JYS\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[0., 0., 1., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [5]:
x_con

array([[ 0.05217877,  0.09475271,  0.57622116, -0.44495321, -0.8072054 ],
       [-0.41260798,  0.40467896, -1.85468155,  1.63469164,  0.33677179],
       [ 0.05217877,  1.92543511,  0.57622116, -0.12805495,  1.48074898],
       ...,
       [ 0.05217877, -0.36339914,  0.49519107, -0.0092181 , -0.34961452],
       [ 0.51696553, -0.71302217,  0.57622116,  0.78302756, -0.8072054 ],
       [ 0.51696553, -0.78294678,  0.49519107, -0.0092181 , -0.34961452]])

In [7]:
import numpy as np
x = np.concatenate([x_cat, x_con], axis=1)
x

array([[ 0.        ,  0.        ,  1.        , ...,  0.57622116,
        -0.44495321, -0.8072054 ],
       [ 0.        ,  0.        ,  0.        , ..., -1.85468155,
         1.63469164,  0.33677179],
       [ 0.        ,  0.        ,  0.        , ...,  0.57622116,
        -0.12805495,  1.48074898],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.49519107,
        -0.0092181 , -0.34961452],
       [ 0.        ,  0.        ,  0.        , ...,  0.57622116,
         0.78302756, -0.8072054 ],
       [ 0.        ,  0.        ,  0.        , ...,  0.49519107,
        -0.0092181 , -0.34961452]])

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_val, y_train, y_val = train_test_split(x, y, random_state=43, test_size=.1)

In [12]:
from lightgbm import LGBMRegressor
lgbm = LGBMRegressor()
lgbm.fit(x_train, y_train)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000126 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 400
[LightGBM] [Info] Number of data points in the train set: 3383, number of used features: 23
[LightGBM] [Info] Start training from score 12368.575820


LGBMRegressor()

In [16]:
import sklearn.metrics as skm
y_pred = lgbm.predict(x_val)
MSE = skm.mean_squared_error
print(MSE(y_val, y_pred)**0.5)

1126.7225727851044


In [24]:
x_test = pd.read_csv('test.csv')
x_test_cat = x_test.select_dtypes('object')
x_test_con = x_test.select_dtypes(exclude='object')

In [25]:
x_test_cat

model transmission fuelType
0            S-MAX       Manual   Diesel
1           Fiesta       Manual   Petrol
2             Kuga       Manual   Petrol
3             Kuga    Semi-Auto   Diesel
4           Fiesta       Manual   Petrol
...            ...          ...      ...
1612        Fiesta       Manual   Petrol
1613         Focus       Manual   Diesel
1614   Grand C-MAX       Manual   Diesel
1615          Kuga       Manual   Diesel
1616         S-MAX    Automatic   Diesel

[1617 rows x 3 columns]

In [26]:
x_test_cat = enc.transform(x_test_cat)
x_test_con = sc.transform(x_test_con)
x_test = np.concatenate([x_test_cat, x_test_con], axis=1)
x_test

array([[ 0.        ,  0.        ,  0.        , ...,  0.17107071,
        -0.12805495,  1.48074898],
       [ 0.        ,  0.        ,  0.        , ...,  0.49519107,
        -1.73235241,  0.33677179],
       [ 0.        ,  0.        ,  0.        , ...,  0.81931143,
        -1.20748966,  0.33677179],
       ...,
       [ 0.        ,  0.        ,  0.        , ..., -1.36850101,
         0.63448149,  0.33677179],
       [ 0.        ,  0.        ,  0.        , ...,  0.17107071,
         0.2284556 ,  1.48074898],
       [ 0.        ,  0.        ,  0.        , ...,  1.46755216,
        -1.0589436 ,  1.48074898]])

In [28]:
pred = lgbm.predict(x_test)
pred

array([15409.03799624, 15519.5625169 , 14448.93577547, ...,
        9575.57890802, 13939.91921542,  5870.67549049])

In [33]:
res = pd.read_csv('sample_submission.csv')
res['price'] = pred
res.to_csv('submission.csv', index=False)